live_config_reload = true

import = ["~/.config/alacritty/themes/aura.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "transparent"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 20
y = 22

[font]
size = 17.0

[font.bold]
family = "Fira Code"
style = "Heavy"

[font.bold_italic]
family = "Fira Code"
style = "Heavy Italic"

[font.italic]
family = "Fira Code"
style = "Medium Italic"

[font.normal]
family = "Fira Code"
style = "Medium"
